export const EN = {
  title: 'User Console',
  subtitle: 'Your account dashboard and token management',
  header: {
    eyebrow: 'User Workspace',
    currentView: 'Current View',
    session: 'Signed in as',
    adminLabel: 'Admin',
    adminMenuAction: 'Admin dashboard',
    announcements: 'Announcements',
    announcementsUnread: 'Announcements ({count})',
    logout: 'Sign out',
    loggingOut: 'Signing out…',
    logoutFailed: 'Failed to sign out: {message}',
    unknownUser: 'Connected user',
    views: {
      dashboard: 'Account Overview',
      billing: 'Entitlements & Orders',
      tokens: 'Token List',
      setup: 'Setup Guide',
      tokenDetail: 'Token Detail',
      oauthCallback: 'OAuth Callback',
    },
    providers: {
      linuxdo: 'LinuxDo',
    },
  },
  announcements: {
    modalAcknowledge: 'Got it',
    tickerOpen: 'Open announcement details: {title}',
    tickerDetails: 'Details',
    tickerClose: 'Dismiss announcement',
    historyTitle: 'Announcements',
    historyDescription: 'Current and archived notices from the service operator.',
    emptyHistory: 'No announcements yet.',
    modal: 'Modal',
    ticker: 'Ticker',
    published: 'Published',
    archived: 'Archived',
    closedAt: 'Dismissed {time}',
  },
  dashboard: {
    usage: 'Account Usage Overview',
    description: 'Track account-level throughput, failures, and quota windows without switching pages.',
    dailySuccess: 'Daily Success',
    dailyFailure: 'Daily Failure',
    monthlySuccess: 'Monthly Success',
    monthlySuccessUtc: 'Monthly Success (UTC)',
    hourlyAny: 'Hourly Any Requests',
    hourly: 'Hourly Business Request Cap',
    daily: 'Daily Credits Cap',
    monthly: 'Monthly Credits Cap',
    debugSharing: 'Share debug information',
    debugSharingHint: 'When enabled, admins may retain request bodies longer according to the debug-sharing policy.',
    debugSharingSaving: 'Updating debug sharing…',
    debugSharingFailed: 'Failed to update debug sharing: {message}',
  },
  setup: {
    title: 'Usage Guide',
    description: 'Choose a Token, then connect Tavily Hikari to your preferred client.',
    tokenLabel: 'Token',
    tokenSelectAria: 'Token used in setup examples',
    emptyTitle: 'No enabled Token available',
    emptyDescription: 'Create or enable a Token before generating client configuration.',
    detailAction: 'Usage Guide',
  },
  billing: {
    title: 'Entitlements & Orders',
    description: 'Understand what is active on this account now, how future natural months are arranged, and what recent recharge orders changed.',
    navAria: 'Console sections',
    summaryTitle: 'Selected month details',
    summaryDescription: 'The durable baseline stays fixed; monthly adjustments and recharge rows follow the month card selected above.',
    currentTotal: 'Current effective quota',
    baseEntitlements: 'Base entitlements',
    monthlyAdjustments: 'Monthly adjustments',
    rechargePackage: 'Recharge package',
    rechargeCredits: 'Recharge monthly credits · {credits}',
    emptyDelta: 'No extra change',
    blockAllNotice: 'A block-all rule is active. Displayed totals are clamped to zero until that rule is removed.',
    pricingTitle: 'Purchase guide',
    pricingDescription: '',
    unitPrice: 'One tier',
    creditStep: 'Tier step',
    monthsRange: 'Active months',
    testPriceEnabled: '',
    unavailableNotice: 'New recharge orders are currently unavailable, but active entitlements and history stay visible.',
    timelineTitle: 'Natural-month schedule',
    timelineDescription: 'Swipe or step across the month cards to compare last month, this month, and any scheduled future quota changes.',
    timelinePrevious: 'Previous month',
    timelineCurrent: 'Current month',
    timelineFuture: 'Scheduled month',
    timelineBack: 'Show previous month',
    timelineForward: 'Show next month',
    timelineSelectMonth: 'Show details for {month}',
    timelinePersistent: 'Persistent total',
    timelineAdjustments: 'Monthly adjustments',
    timelineRecharge: 'Recharge',
    timelineEffective: 'Effective total',
    timelineRechargeCredits: '{credits} monthly credits',
    timelineNoFuture: 'No future natural-month schedule is active right now.',
    timelineNoScheduledChanges: 'No time-limited entitlements are scheduled beyond the durable baseline right now.',
    ordersTitle: 'Recent orders',
    ordersDescription: 'Recent recharge orders and the quota they add at the quote month.',
    orderCreatedAt: 'Created {time}',
    orderImpact: '+{hourly} requests/hour · +{daily} credits/day · +{monthly} credits/month',
    orderClampApplied: 'Current-month clamp applied',
    ordersPageSummary: 'Page {page} / {totalPages} · {total} orders',
    ordersPreviousPage: 'Previous',
    ordersNextPage: 'Next',
  },
  recharge: {
    title: 'Monthly-credit recharge',
    description: 'Increase the monthly-credit quota applied to this month and upcoming natural months.',
    enabled: 'Available',
    disabled: 'Unavailable',
    currentEntitlement: 'Purchased quota this month',
    currentMonthFinal: 'Current final quota',
    effectiveUntil: 'Effective until',
    noEntitlement: 'No active package',
    credits: 'Monthly-credit tier',
    months: 'Natural months',
    quotaDelta: 'Quota increase',
    hourlyDelta: 'Hourly',
    dailyDelta: 'Daily',
    monthlyDelta: 'Monthly',
    testPrice: '',
    amount: 'Pay',
    discountedAmount: 'Discounted pay',
    discountNotice: 'The current month is priced by the remaining days.',
    clampNotice: 'Priced by remaining days this month',
    preview: 'Preview',
    previewTitle: 'Order impact preview',
    previewDescription: 'Review how this recharge changes quota by month before creating an order.',
    previewScopeNote: 'This preview only shows what the new recharge adds. Base entitlements stay unchanged.',
    previewMonth: 'Month',
    previewCurrentQuota: 'Before order',
    previewCurrentQuotaHint: 'Recharge quota already scheduled for this month before this order. It excludes base quota and other adjustments.',
    previewDelta: 'Added by order',
    previewDeltaHint: "Recharge quota this order adds after payment succeeds. The current month may be prorated by remaining days; later months receive the full selected tier.",
    previewExpectedQuota: 'After order',
    previewExpectedQuotaHint: "Recharge quota scheduled for this month after payment succeeds: the quota before this order plus this order's addition. It excludes base quota and other adjustments.",
    previewFieldHelpLabel: 'Explain the recharge preview columns',
    previewAfterExpiry: 'After expiry',
    closePreview: 'Close',
    create: 'Create order',
    creating: 'Creating…',
    createFailed: 'Failed to create order: {message}',
    quoteFailed: 'Failed to refresh quote: {message}',
    unavailable: 'Recharge is not configured on this server.',
    orders: 'Recent orders',
    noOrders: 'No recharge orders yet.',
    status: {
      pending: 'Pending',
      paid: 'Paid',
      failed: 'Failed',
      expired: 'Closed',
      cancelled: 'Cancelled',
      refunding: 'Refunding',
      refunded: 'Refunded',
      refundOnly: 'Refund only',
    },
    orderStatusDetail: {
      pending: 'Payment closes {time}',
      paid: 'Paid {time}',
      failed: 'Payment failed',
      expired: 'Payment entry closed {time}',
      cancelled: 'Order cancelled {time}',
      refunding: 'Paid late. Automatic refund is in progress.',
      refunded: 'Late payment was refunded automatically.',
      refundOnly: 'Refund completed. Benefits were kept.',
      refundRetryAt: 'Next retry {time}',
    },
  },
  tokens: {
    title: 'Token List',
    description: 'Copy tokens, review token status and success stats, and open recent request details.',
    summary: {
      total: 'Tokens',
      enabled: 'Enabled',
      dailySuccess: 'Daily Success',
    },
    loading: 'Loading token list…',
    empty: 'No token available for this account.',
    copy: 'Copy',
    copied: 'Copied',
    copyFailed: 'Copy failed',
    detail: 'Details',
    reset: 'Reset',
    resetDialog: {
      title: 'Reset Token',
      description: 'This will generate a new full token for {tokenId}. The current token stops working immediately.',
      cancel: 'Cancel',
      confirm: 'Reset',
      running: 'Resetting…',
      failed: 'Failed to reset token: {message}',
    },
    resetResult: {
      title: 'New Token Generated',
      copied: 'The new token was copied to clipboard.',
      copyBlocked: 'Automatic copy was blocked. The new token is selected below for manual copy.',
      fieldLabel: 'New Token',
      close: 'Close',
      copy: 'Copy',
      copyFailed: 'Copy Failed',
    },
    manualCopy: {
      title: 'Manual copy required',
      description: 'This browser blocked automatic copy. The full token is selected below for manual copy.',
      fieldLabel: 'Full Token',
      close: 'Close',
    },
    table: {
      id: 'Token ID',
      status: 'Status & Activity',
      stats: 'Usage Stats',
      enabled: 'Enabled',
      disabled: 'Disabled',
      lastUsed: 'Last Used',
      neverUsed: 'No recent requests',
      dailySuccess: 'Daily Success',
      dailyFailure: 'Daily Failure',
      monthlySuccess: 'Monthly Success',
      actions: 'Actions',
    },
  },
  unavailable: {
    title: 'User console unavailable',
    description: 'This server has not enabled user OAuth login, so `/console` cannot load dashboard or token data right now.',
    home: 'Back to Home',
  },
  loggedOut: {
    title: 'You have signed out',
    description: 'Sign in again to view your dashboard and token data.',
    action: 'Sign in with LinuxDo',
  },
  loginRequired: {
    title: 'Sign in to open your console',
    description: 'Dashboard and token data appear here after you sign in with LinuxDo.',
    action: 'Sign in with LinuxDo',
  },
  oauthCallback: {
    badge: 'OAuth Callback',
    status: {
      connecting: {
        title: 'Talking to {provider}',
        description: 'Please wait while we verify the callback and open your console session.',
      },
      success: {
        title: '{provider} connected',
        description: 'Your console session is ready. Redirecting to `/console` now.',
      },
      providerDenied: {
        title: '{provider} authorization was cancelled',
        description: 'The provider did not grant access, so no console session was created.',
      },
      invalidRequest: {
        title: 'This callback link is incomplete',
        description: 'The provider return did not include the required authorization fields.',
      },
      invalidState: {
        title: 'This login attempt has expired',
        description: 'The callback can no longer be verified. Start a fresh {provider} login to continue.',
      },
      inactiveUser: {
        title: '{provider} account unavailable',
        description: 'This LinuxDo account is currently marked inactive and cannot open a console session.',
      },
      timeout: {
        title: 'The connection took too long',
        description: 'We did not receive a completion signal in time. Start a fresh {provider} login instead of retrying this callback.',
      },
      upstreamFailure: {
        title: 'We could not finish the {provider} handshake',
        description: 'The service could not exchange the authorization with {provider} right now.',
      },
      serverError: {
        title: 'This callback could not be completed',
        description: 'The console could not finish the local sign-in flow. Start a fresh {provider} login when ready.',
      },
      unsupportedProvider: {
        title: 'This provider is not available here yet',
        description: 'This callback shell is ready for future providers, but this deployment currently only supports LinuxDo.',
      },
    },
    steps: {
      returned: 'OAuth callback returned',
      verify: 'Secure state verification',
      session: 'Console session ready',
    },
    actions: {
      retry: 'Reconnect with {provider}',
      home: 'Back to Home',
    },
    notes: {
      connecting: 'Keep this tab open for a moment while the console finishes the handoff.',
      redirecting: 'You are being forwarded to your console workspace.',
      timeout: 'For safety, the previous authorization code will not be reused.',
      providerDetail: 'Provider detail: {detail}',
      technicalDetail: 'Technical detail: {detail}',
    },
  },
  detail: {
    title: 'Token Detail',
    subtitle: 'Review this token’s quota, secret, connectivity checks, and recent requests.',
    subtitleShort: 'Quota, secret, checks, and requests.',
    back: 'Back to Token List',
    backShort: 'Back',
    tokenLabel: 'Token',
    tokenSecret: {
      show: 'Show full token',
      hide: 'Hide full token',
      iconAlt: 'token visibility toggle',
      loading: 'Loading full token…',
      revealFailed: 'Failed to reveal token: {message}',
    },
    guideToken: {
      show: 'Show token',
      hide: 'Hide token',
      loading: 'Loading token…',
      revealFailed: 'Failed to reveal guide token: {message}',
    },
    probe: {
      title: 'Connectivity Checks',
      costHint: "This check uses this token's own quota/credits.",
      costHintAria: 'Quota usage hint',
      mcpButton: {
        idle: 'Test MCP',
        success: 'MCP Ready',
        partial: 'MCP Partial',
        failed: 'MCP Failed',
      },
      apiButton: {
        idle: 'Test API',
        success: 'API Ready',
        partial: 'API Partial',
        failed: 'API Failed',
      },
      runningButton: '{label} {done}/{total}',
      running: 'Checking: {step}',
      preflightFailed: 'Cannot load token secret: {message}',
      summarySuccess: '{passed}/{total} checks passed',
      summaryPartial: '{passed}/{total} checks passed, {failed} failed',
      stepOk: 'OK',
      stepStatus: {
        running: 'Running',
        success: 'Success',
        failed: 'Failed',
        blocked: 'Blocked',
        skipped: 'Skipped',
      },
      quotaBlocked: '{window} quota exhausted, skipping billable MCP tool calls.',
      quotaWindows: {
        hour: 'Hourly',
        day: 'Daily',
        month: 'Monthly',
      },
      bubbles: {
        mcpTitle: 'MCP Probe',
        apiTitle: 'API Probe',
        current: 'Current',
        result: 'Result',
        preflight: 'Token Secret',
        done: 'Summary',
      },
      steps: {
        mcpInitialize: 'MCP session initialize',
        mcpInitialized: 'MCP initialized notification',
        mcpPing: 'MCP service connectivity',
        mcpToolsList: 'MCP tool discovery',
        mcpToolCall: 'Call {tool} tool',
        apiSearch: 'Web search capability',
        apiExtract: 'Page extract capability',
        apiCrawl: 'Site crawl capability',
        apiMap: 'Site map capability',
        apiResearch: 'Research task creation',
        apiResearchResult: 'Research result query',
        apiUsage: 'Usage boundary check',
      },
      skippedProbeFixture: 'No local probe fixture for {tool}; skipped.',
      errors: {
        missingAdvertisedTools: 'MCP tools/list returned no tools',
        missingRequestId: 'Research request_id is missing',
        researchFailed: 'Research task failed',
        researchUnexpectedStatus: 'Research returned unsupported status: {status}',
        usageLeakedUpstreamField: 'Usage response leaked upstream account field: {field}',
      },
      researchPendingAccepted: 'pending (accepted)',
      researchStatus: 'status={status}',
    },
    logs: 'Recent Requests (50)',
    logsSubtitle: 'Review the latest request records for this token.',
    logsBack: 'Back to Token Detail',
    mobileOpen: 'View recent requests',
    mobileSummary: 'Latest 50 requests with quota-usage filter',
    mobileAction: '›',
    logFilters: {
      ariaLabel: 'Recent request billing filter',
      all: 'All',
      billable: 'Quota usage',
    },
    pushStatus: {
      ariaLabel: 'Real-time request log push status',
      browserUnsupported:
        'Real-time request log push is unavailable because this browser does not support server-sent events.',
      reconnecting:
        'Real-time request log push is reconnecting. Recent request updates may lag until the stream resumes.',
      closed: 'Real-time request log push connection is unavailable. Refresh the page or try again later.',
    },
    emptyLogs: 'No recent requests.',
    table: {
      request: 'Request',
      transport: 'HTTP / Tavily',
      path: 'Path',
      time: 'Time',
      http: 'HTTP',
      mcp: 'Tavily',
      credits: 'Credits',
      result: 'Result',
      error: 'Error',
    },
    noQuery: 'No query string',
    noError: 'No error message',
  },
  errors: {
    load: 'Failed to load console data',
    detail: 'Failed to load token detail',
  },
  footer: {
    title: 'Tavily Hikari User Console',
    githubAria: 'Open GitHub repository',
    githubLabel: 'GitHub',
    loadingVersion: '· Loading version…',
    errorVersion: '· Version unavailable',
    tagPrefix: '· ',
  },
}

export const ZH = {
  title: '用户控制台',
  subtitle: '账户仪表盘与 Token 管理',
  header: {
    eyebrow: '用户工作区',
    currentView: '当前视图',
    session: '当前身份',
    adminLabel: '管理员',
    adminMenuAction: '管理员面板',
    announcements: '公告',
    announcementsUnread: '公告（{count}）',
    logout: '退出登录',
    loggingOut: '退出中…',
    logoutFailed: '退出登录失败：{message}',
    unknownUser: '已连接用户',
    views: {
      dashboard: '账户概览',
      billing: '权益与订单',
      tokens: 'Token 列表',
      setup: '使用方法',
      tokenDetail: 'Token 详情',
      oauthCallback: 'OAuth 回调',
    },
    providers: {
      linuxdo: 'LinuxDo',
    },
  },
  announcements: {
    modalAcknowledge: '知道了',
    tickerOpen: '查看公告详情：{title}',
    tickerDetails: '详情',
    tickerClose: '关闭公告',
    historyTitle: '公告',
    historyDescription: '查看服务管理员发布的当前与历史公告。',
    emptyHistory: '暂无公告。',
    modal: '弹窗',
    ticker: '横幅',
    published: '发布中',
    archived: '已归档',
    closedAt: '已于 {time} 关闭',
  },
  dashboard: {
    usage: '账户用量概览',
    description: '在同一页集中查看账户级成功率、失败量与各配额窗口。',
    dailySuccess: '今日成功',
    dailyFailure: '今日失败',
    monthlySuccess: '本月成功',
    monthlySuccessUtc: '本月成功（UTC）',
    hourlyAny: '每小时任意请求',
    hourly: '每小时业务请求次数限额',
    daily: '每日积分限额',
    monthly: '每月积分限额',
    debugSharing: '共享调试信息',
    debugSharingHint: '开启后，管理员可按共享调试策略延长请求 body 保留时间。',
    debugSharingSaving: '正在更新调试共享…',
    debugSharingFailed: '更新调试共享失败：{message}',
  },
  setup: {
    title: '使用方法',
    description: '选择一个 Token，然后按所用客户端完成 Tavily Hikari 接入。',
    tokenLabel: 'Token',
    tokenSelectAria: '选择用于接入示例的 Token',
    emptyTitle: '暂无可用 Token',
    emptyDescription: '请先创建或启用 Token，再生成客户端接入配置。',
    detailAction: '使用方法',
  },
  billing: {
    title: '权益与订单',
    description: '在同一页读清当前生效权益、后续自然月安排，以及近期充值订单带来的变化。',
    navAria: '控制台分区',
    summaryTitle: '所选月份详情',
    summaryDescription: '长期基线保持不变；下方月度调整和充值权益会跟随上方选中的月份卡片切换。',
    currentTotal: '当前生效额度',
    baseEntitlements: '基础权益',
    monthlyAdjustments: '月度调整',
    rechargePackage: '充值权益',
    rechargeCredits: '充值月积分 · {credits}',
    emptyDelta: '当前无额外变化',
    blockAllNotice: '当前存在 block-all 规则，展示额度会被压到 0，直到该规则解除。',
    pricingTitle: '购买说明',
    pricingDescription: '',
    unitPrice: '一个档位',
    creditStep: '每次加购',
    monthsRange: '生效月数',
    testPriceEnabled: '',
    unavailableNotice: '当前暂不接受新的充值订单，但已生效权益和历史订单仍会展示。',
    timelineTitle: '自然月安排',
    timelineDescription: '左右切换月历卡片，对比上个月、本月以及后续排期中的额度变化。',
    timelinePrevious: '上个月',
    timelineCurrent: '当前月',
    timelineFuture: '后续月份',
    timelineBack: '查看上个月',
    timelineForward: '查看下个月',
    timelineSelectMonth: '查看 {month} 详情',
    timelinePersistent: '持续额度',
    timelineAdjustments: '月度调整',
    timelineRecharge: '充值权益',
    timelineEffective: '最终额度',
    timelineRechargeCredits: '{credits} 月积分',
    timelineNoFuture: '当前没有额外的后续自然月安排。',
    timelineNoScheduledChanges: '除持续有效的基础额度外，当前没有额外排期中的时效权益。',
    ordersTitle: '近期订单',
    ordersDescription: '查看最近充值订单，以及它们在报价月份带来的额度变化。',
    orderCreatedAt: '创建于 {time}',
    orderImpact: '+{hourly} 次/小时 · +{daily} 积分/日 · +{monthly} 积分/月',
    orderClampApplied: '当前月已折抵',
    ordersPageSummary: '第 {page} / {totalPages} 页 · 共 {total} 单',
    ordersPreviousPage: '上一页',
    ordersNextPage: '下一页',
  },
  recharge: {
    title: '月积分充值',
    description: '为当前账户增加本月和后续自然月的月积分额度。',
    enabled: '可用',
    disabled: '不可用',
    currentEntitlement: '本月已购额度',
    currentMonthFinal: '本月最终额度',
    effectiveUntil: '权益有效至',
    noEntitlement: '暂无生效权益',
    credits: '月积分档位',
    months: '自然月数',
    quotaDelta: '额度增量',
    hourlyDelta: '小时',
    dailyDelta: '日',
    monthlyDelta: '月',
    testPrice: '',
    amount: '应付',
    discountedAmount: '折后应付',
    discountNotice: '本月会按剩余天数折算价格。',
    clampNotice: '本月按剩余天数折算',
    preview: '预览',
    previewTitle: '订单影响预览',
    previewDescription: '创建订单前，查看本次充值会如何影响每个月的额度。',
    previewScopeNote: '这里只看本次充值会增加多少，不影响基础权益。',
    previewMonth: '月份',
    previewCurrentQuota: '本单前充值月额度',
    previewCurrentQuotaHint: '创建本单前，该月份已经生效的充值月额度。不包含基础额度或其他额度调整。',
    previewDelta: '本单增加',
    previewDeltaHint: '本单支付成功后，该月份新增的充值月额度。本月可能按剩余天数折算，后续月份按完整档位增加。',
    previewExpectedQuota: '本单后充值月额度',
    previewExpectedQuotaHint: '本单支付成功后，该月份的充值月额度合计，即本单前充值月额度加上本单增加。不包含基础额度或其他额度调整。',
    previewFieldHelpLabel: '查看充值预览字段说明',
    previewAfterExpiry: '到期后',
    closePreview: '关闭',
    create: '创建订单',
    creating: '创建中…',
    createFailed: '创建订单失败：{message}',
    quoteFailed: '刷新报价失败：{message}',
    unavailable: '当前服务尚未配置充值功能。',
    orders: '近期订单',
    noOrders: '暂无充值订单。',
    status: {
      pending: '待支付',
      paid: '已支付',
      failed: '失败',
      expired: '已关闭',
      cancelled: '已取消',
      refunding: '退款中',
      refunded: '已退款',
      refundOnly: '仅退款',
    },
    orderStatusDetail: {
      pending: '支付入口将于 {time} 关闭',
      paid: '已于 {time} 支付',
      failed: '支付失败',
      expired: '支付入口已于 {time} 关闭',
      cancelled: '订单已于 {time} 取消',
      refunding: '已晚到支付，系统正在原路退款。',
      refunded: '晚到支付已自动原路退款。',
      refundOnly: '退款已完成，权益保留。',
      refundRetryAt: '下次重试 {time}',
    },
  },
  tokens: {
    title: 'Token 列表',
    description: '复制 Token、查看状态与成功统计，并进入详情检查最近请求。',
    summary: {
      total: 'Token 数',
      enabled: '启用中',
      dailySuccess: '今日成功',
    },
    loading: 'Token 列表加载中…',
    empty: '当前账户暂无 Token。',
    copy: '复制',
    copied: '已复制',
    copyFailed: '复制失败',
    detail: '详情',
    reset: '重置',
    resetDialog: {
      title: '重置 Token',
      description: '这会为 {tokenId} 生成新的完整 Token，当前 Token 会立即失效。',
      cancel: '取消',
      confirm: '重置',
      running: '重置中…',
      failed: '重置 Token 失败：{message}',
    },
    resetResult: {
      title: '新 Token 已生成',
      copied: '新的 Token 已复制到剪贴板。',
      copyBlocked: '当前浏览器拦截了自动复制，下面已选中新 Token，可直接手动复制。',
      fieldLabel: '新 Token',
      close: '关闭',
      copy: '复制',
      copyFailed: '复制失败',
    },
    manualCopy: {
      title: '请手动复制',
      description: '当前浏览器拦截了自动复制，下面已选中完整 Token，可直接手动复制。',
      fieldLabel: '完整 Token',
      close: '关闭',
    },
    table: {
      id: 'Token ID',
      status: '状态与最近使用',
      stats: '用量统计',
      enabled: '启用中',
      disabled: '已停用',
      lastUsed: '最近使用',
      neverUsed: '暂无最近请求',
      dailySuccess: '今日成功',
      dailyFailure: '今日失败',
      monthlySuccess: '本月成功',
      actions: '操作',
    },
  },
  unavailable: {
    title: '用户控制台暂不可用',
    description: '当前服务未启用用户 OAuth 登录，因此 `/console` 暂时无法加载账户仪表盘与 Token 数据。',
    home: '返回首页',
  },
  loggedOut: {
    title: '你已退出登录',
    description: '重新登录后即可查看账户仪表盘与 Token 数据。',
    action: '使用 LinuxDo 登录',
  },
  loginRequired: {
    title: '登录后即可打开控制台',
    description: '使用 LinuxDo 登录后，这里就会显示你的仪表盘与 Token 数据。',
    action: '使用 LinuxDo 登录',
  },
  oauthCallback: {
    badge: 'OAuth 回调',
    status: {
      connecting: {
        title: '正在与 {provider} 通信',
        description: '请稍候，正在校验回调并为你建立控制台会话。',
      },
      success: {
        title: '{provider} 已连接',
        description: '控制台会话已经准备好，正在跳转到 `/console`。',
      },
      providerDenied: {
        title: '{provider} 授权已取消',
        description: '提供方没有授予访问权限，因此这次不会创建控制台会话。',
      },
      invalidRequest: {
        title: '这条回调链接不完整',
        description: '提供方返回里缺少必要的授权字段，无法继续完成登录。',
      },
      invalidState: {
        title: '这次登录尝试已经失效',
        description: '当前回调已无法通过校验，请重新发起一次 {provider} 登录。',
      },
      inactiveUser: {
        title: '{provider} 账户当前不可用',
        description: '这个 LinuxDo 账户当前被标记为 inactive，暂时无法打开控制台会话。',
      },
      timeout: {
        title: '等待时间有点久了',
        description: '我们没有在超时预算内拿到完成信号。请重新发起一次 {provider} 登录，不要重试这次旧回调。',
      },
      upstreamFailure: {
        title: '暂时无法完成与 {provider} 的握手',
        description: '服务端暂时无法和 {provider} 完成授权交换。',
      },
      serverError: {
        title: '这次回调没能完成',
        description: '控制台没能完成本地登录收口。准备好后请重新发起一次 {provider} 登录。',
      },
      unsupportedProvider: {
        title: '当前部署还不支持这个提供方',
        description: '这套回调壳已预留多提供方入口，但当前部署暂时只接入 LinuxDo。',
      },
    },
    steps: {
      returned: 'OAuth 回调已返回',
      verify: '安全状态校验',
      session: '控制台会话就绪',
    },
    actions: {
      retry: '重新连接 {provider}',
      home: '返回首页',
    },
    notes: {
      connecting: '请先别关掉这个页面，控制台正在完成最后的承接。',
      redirecting: '马上带你进入控制台工作区。',
      timeout: '为了安全起见，旧授权码不会被重复使用。',
      providerDetail: '提供方信息：{detail}',
      technicalDetail: '技术细节：{detail}',
    },
  },
  detail: {
    title: 'Token 详情',
    subtitle: '查看当前 Token 的配额、密钥、连通性检测与最近请求。',
    subtitleShort: '查看配额、密钥、检测与请求。',
    back: '返回 Token 列表',
    backShort: '返回',
    tokenLabel: 'Token',
    tokenSecret: {
      show: '显示完整 Token',
      hide: '隐藏完整 Token',
      iconAlt: 'Token 显隐切换',
      loading: '正在读取完整 Token…',
      revealFailed: '读取完整 Token 失败：{message}',
    },
    guideToken: {
      show: '显示密钥',
      hide: '隐藏密钥',
      loading: '正在读取密钥…',
      revealFailed: '读取导览密钥失败：{message}',
    },
    probe: {
      title: '连通性检测',
      costHint: '该检测会消耗当前 Token 自身额度。',
      costHintAria: '额度消耗提示',
      mcpButton: {
        idle: '检测 MCP',
        success: 'MCP 就绪',
        partial: 'MCP 部分通过',
        failed: 'MCP 失败',
      },
      apiButton: {
        idle: '检测 API',
        success: 'API 就绪',
        partial: 'API 部分通过',
        failed: 'API 失败',
      },
      runningButton: '{label} {done}/{total}',
      running: '检测中：{step}',
      preflightFailed: '读取 Token 失败：{message}',
      summarySuccess: '{passed}/{total} 项通过',
      summaryPartial: '{passed}/{total} 项通过，{failed} 项失败',
      stepOk: '通过',
      stepStatus: {
        running: '进行中',
        success: '成功',
        failed: '失败',
        blocked: '受阻',
        skipped: '已跳过',
      },
      quotaBlocked: '{window}配额已耗尽，已跳过会消耗额度的 MCP 工具调用。',
      quotaWindows: {
        hour: '小时',
        day: '日',
        month: '月',
      },
      bubbles: {
        mcpTitle: 'MCP 检测',
        apiTitle: 'API 检测',
        current: '当前检测',
        result: '结果',
        preflight: '读取 Token',
        done: '汇总',
      },
      steps: {
        mcpInitialize: 'MCP 会话初始化',
        mcpInitialized: 'MCP initialized 通知',
        mcpPing: 'MCP 服务连通',
        mcpToolsList: 'MCP 工具发现',
        mcpToolCall: '调用 {tool} 工具',
        apiSearch: '网页搜索能力',
        apiExtract: '页面抽取能力',
        apiCrawl: '站点抓取能力',
        apiMap: '站点映射能力',
        apiResearch: '研究任务创建',
        apiResearchResult: '研究结果查询',
        apiUsage: '用量边界检查',
      },
      skippedProbeFixture: '当前本地没有 {tool} 的检测夹具，已跳过。',
      errors: {
        missingAdvertisedTools: 'MCP tools/list 没有返回任何工具',
        missingRequestId: 'research 响应缺少 request_id',
        researchFailed: 'research 任务失败',
        researchUnexpectedStatus: 'research 返回了不支持的状态：{status}',
        usageLeakedUpstreamField: '用量响应泄露了上游账号字段：{field}',
      },
      researchPendingAccepted: 'pending（已受理）',
      researchStatus: '状态={status}',
    },
    logs: '近期请求（50 条）',
    logsSubtitle: '查看该 Token 的最近请求记录。',
    logsBack: '返回 Token 详情',
    mobileOpen: '查看近期请求',
    mobileSummary: '最近 50 条请求，含额度消耗筛选',
    mobileAction: '›',
    logFilters: {
      ariaLabel: '近期请求额度筛选',
      all: '全部',
      billable: '额度消耗',
    },
    pushStatus: {
      ariaLabel: '实时请求日志推送状态',
      browserUnsupported: '当前浏览器不支持服务器推送事件，实时请求日志推送不可用。',
      reconnecting: '实时请求日志推送正在重连，恢复前最近请求列表可能会有延迟。',
      closed: '实时请求日志推送连接当前不可用，请刷新页面或稍后再试。',
    },
    emptyLogs: '暂无请求记录。',
    table: {
      request: '请求',
      transport: 'HTTP / Tavily',
      path: '路径',
      time: '时间',
      http: 'HTTP',
      mcp: 'Tavily',
      credits: '积分',
      result: '结果',
      error: '错误',
    },
    noQuery: '无查询参数',
    noError: '无错误信息',
  },
  errors: {
    load: '加载控制台数据失败',
    detail: '加载 Token 详情失败',
  },
  footer: {
    title: 'Tavily Hikari 用户控制台',
    githubAria: '打开 GitHub 仓库',
    githubLabel: 'GitHub',
    loadingVersion: '· 正在读取版本…',
    errorVersion: '· 版本不可用',
    tagPrefix: '· ',
  },
}
