import type { AdminRechargeListResponse, AdminTotpStatus } from '../../api'

const now = Math.floor(Date.now() / 1000)

export const rechargeStoryData: AdminRechargeListResponse = {
  hasRechargeOrders: true,
  total: 6,
  page: 1,
  perPage: 25,
  items: [
    {
      outTradeNo: 'ldc_202605_0001',
      user: { id: 'usr_alice', displayName: 'Alice Chen', username: 'alice', avatarTemplate: null },
      status: 'paid',
      credits: 3000,
      months: 3,
      moneyCents: 45000,
      money: '450.00',
      quoteMonthStart: now - 86400 * 21,
      finalMoneyCents: 45000,
      finalHourlyDelta: 60,
      finalDailyDelta: 300,
      finalMonthlyDelta: 3000,
      monthEndClampApplied: false,
      tradeNo: 'linuxdo-trade-1001',
      paymentUrl: null,
      orderName: 'Tavily Hikari 3000 credits x 3 month(s)',
      createdAt: now - 86400 * 18,
      payExpiresAt: now - 86400 * 18 + 600,
      cancelAfterAt: now - 86400 * 17,
      cancelledAt: null,
      updatedAt: now - 86400 * 18 + 120,
      paidAt: now - 86400 * 18 + 120,
      refundedAt: null,
      refundActor: null,
      lastNotifyAt: now - 86400 * 18 + 120,
      refundRetryAfterAt: null,
      refundAttempts: 0,
      lastError: null,
    },
    {
      outTradeNo: 'ldc_202605_0002',
      user: { id: 'usr_alice', displayName: 'Alice Chen', username: 'alice', avatarTemplate: null },
      status: 'cancelled',
      credits: 1000,
      months: 1,
      moneyCents: 5000,
      money: '50.00',
      quoteMonthStart: now - 86400 * 4,
      finalMoneyCents: 5000,
      finalHourlyDelta: 20,
      finalDailyDelta: 100,
      finalMonthlyDelta: 1000,
      monthEndClampApplied: false,
      tradeNo: null,
      paymentUrl: null,
      orderName: 'Tavily Hikari 1000 credits x 1 month(s)',
      createdAt: now - 90_000,
      payExpiresAt: now - 89_400,
      cancelAfterAt: now - 3600,
      cancelledAt: now - 3540,
      updatedAt: now - 3540,
      paidAt: null,
      refundedAt: null,
      refundActor: null,
      lastNotifyAt: null,
      refundRetryAfterAt: null,
      refundAttempts: 0,
      lastError: 'order cancelled after 24 hours',
    },
    {
      outTradeNo: 'ldc_202605_0003',
      user: { id: 'usr_bob', displayName: 'Bob Lin', username: 'bob', avatarTemplate: null },
      status: 'refundOnly',
      credits: 1000,
      months: 1,
      moneyCents: 5000,
      money: '50.00',
      quoteMonthStart: now - 86400 * 9,
      finalMoneyCents: 5000,
      finalHourlyDelta: 20,
      finalDailyDelta: 100,
      finalMonthlyDelta: 1000,
      monthEndClampApplied: false,
      tradeNo: 'linuxdo-trade-1002',
      paymentUrl: null,
      orderName: 'Tavily Hikari 1000 credits x 1 month(s)',
      createdAt: now - 86400 * 8,
      payExpiresAt: now - 86400 * 8 + 600,
      cancelAfterAt: now - 86400 * 7,
      cancelledAt: null,
      updatedAt: now - 86400 * 7,
      paidAt: now - 86400 * 8 + 90,
      refundedAt: now - 86400 * 7,
      refundActor: 'builtin-admin',
      lastNotifyAt: now - 86400 * 8 + 90,
      refundRetryAfterAt: null,
      refundAttempts: 0,
      lastError: null,
    },
    {
      outTradeNo: 'ldc_202605_0004',
      user: { id: 'usr_cora', displayName: 'Cora Wu', username: 'cora', avatarTemplate: null },
      status: 'expired',
      credits: 1000,
      months: 1,
      moneyCents: 5000,
      money: '30.00',
      quoteMonthStart: now - 86400 * 2,
      finalMoneyCents: 3000,
      finalHourlyDelta: 12,
      finalDailyDelta: 60,
      finalMonthlyDelta: 600,
      monthEndClampApplied: true,
      tradeNo: null,
      paymentUrl: null,
      orderName: 'Tavily Hikari 1000 credits x 1 month(s)',
      createdAt: now - 3600 * 2,
      payExpiresAt: now - 3600 + 600,
      cancelAfterAt: now + 79_200,
      cancelledAt: null,
      updatedAt: now - 3600 + 600,
      paidAt: null,
      refundedAt: null,
      refundActor: null,
      lastNotifyAt: null,
      refundRetryAfterAt: null,
      refundAttempts: 0,
      lastError: 'payment entry closed locally after 10 minutes',
    },
    {
      outTradeNo: 'ldc_202605_0005',
      user: { id: 'usr_dana', displayName: 'Dana He', username: 'dana', avatarTemplate: null },
      status: 'refunding',
      credits: 1000,
      months: 1,
      moneyCents: 3000,
      money: '30.00',
      quoteMonthStart: now - 86400,
      finalMoneyCents: 3000,
      finalHourlyDelta: 12,
      finalDailyDelta: 60,
      finalMonthlyDelta: 600,
      monthEndClampApplied: true,
      tradeNo: 'linuxdo-trade-1005',
      paymentUrl: null,
      orderName: 'Tavily Hikari 1000 credits x 1 month(s)',
      createdAt: now - 86_400,
      payExpiresAt: now - 85_800,
      cancelAfterAt: now,
      cancelledAt: null,
      updatedAt: now - 180,
      paidAt: now - 900,
      refundedAt: null,
      refundActor: 'system:auto',
      lastNotifyAt: now - 840,
      refundRetryAfterAt: now + 300,
      refundAttempts: 2,
      lastError: 'paid month no longer matches quote month',
    },
    {
      outTradeNo: 'ldc_202605_0006',
      user: { id: 'usr_eli', displayName: 'Eli Sun', username: 'eli', avatarTemplate: null },
      status: 'refunded',
      credits: 1000,
      months: 1,
      moneyCents: 3000,
      money: '30.00',
      quoteMonthStart: now - 86400 * 3,
      finalMoneyCents: 3000,
      finalHourlyDelta: 12,
      finalDailyDelta: 60,
      finalMonthlyDelta: 600,
      monthEndClampApplied: true,
      tradeNo: 'linuxdo-trade-1006',
      paymentUrl: null,
      orderName: 'Tavily Hikari 1000 credits x 1 month(s)',
      createdAt: now - 86400 * 3,
      payExpiresAt: now - 86400 * 3 + 600,
      cancelAfterAt: now - 86400 * 2,
      cancelledAt: null,
      updatedAt: now - 86400 * 2 + 1800,
      paidAt: now - 86400 * 2 + 900,
      refundedAt: now - 86400 * 2 + 1800,
      refundActor: 'system:auto',
      lastNotifyAt: now - 86400 * 2 + 960,
      refundRetryAfterAt: null,
      refundAttempts: 1,
      lastError: null,
    },
  ],
  groups: [
    {
      user: { id: 'usr_alice', displayName: 'Alice Chen', username: 'alice', avatarTemplate: null },
      orderCount: 2,
      paidOrderCount: 1,
      refundedOrderCount: 0,
      totalCredits: 4000,
      totalMoneyCents: 50000,
      latestOrderCreatedAt: now - 90_000,
      latestPaidAt: now - 86400 * 18 + 120,
      latestRefundedAt: null,
    },
    {
      user: { id: 'usr_bob', displayName: 'Bob Lin', username: 'bob', avatarTemplate: null },
      orderCount: 1,
      paidOrderCount: 0,
      refundedOrderCount: 1,
      totalCredits: 1000,
      totalMoneyCents: 5000,
      latestOrderCreatedAt: now - 86400 * 8,
      latestPaidAt: now - 86400 * 8 + 90,
      latestRefundedAt: now - 86400 * 7,
    },
    {
      user: { id: 'usr_cora', displayName: 'Cora Wu', username: 'cora', avatarTemplate: null },
      orderCount: 1,
      paidOrderCount: 0,
      refundedOrderCount: 0,
      totalCredits: 1000,
      totalMoneyCents: 3000,
      latestOrderCreatedAt: now - 3600 * 2,
      latestPaidAt: null,
      latestRefundedAt: null,
    },
    {
      user: { id: 'usr_dana', displayName: 'Dana He', username: 'dana', avatarTemplate: null },
      orderCount: 1,
      paidOrderCount: 1,
      refundedOrderCount: 0,
      totalCredits: 1000,
      totalMoneyCents: 3000,
      latestOrderCreatedAt: now - 86400,
      latestPaidAt: now - 900,
      latestRefundedAt: null,
    },
    {
      user: { id: 'usr_eli', displayName: 'Eli Sun', username: 'eli', avatarTemplate: null },
      orderCount: 1,
      paidOrderCount: 1,
      refundedOrderCount: 1,
      totalCredits: 1000,
      totalMoneyCents: 3000,
      latestOrderCreatedAt: now - 86400 * 3,
      latestPaidAt: now - 86400 * 2 + 900,
      latestRefundedAt: now - 86400 * 2 + 1800,
    },
  ],
}

export const emptyRechargeStoryData: AdminRechargeListResponse = {
  hasRechargeOrders: false,
  items: [],
  groups: [],
  total: 0,
  page: 1,
  perPage: 25,
}

export const boundRechargeTotpStatus: AdminTotpStatus = {
  enabled: true,
  available: true,
  rechargeFeatureEnabled: true,
  missingCryptoKey: false,
  lockedUntil: null,
  issuer: 'Tavily Hikari',
  accountName: 'admin-recharge',
}

export const unboundRechargeTotpStatus: AdminTotpStatus = {
  ...boundRechargeTotpStatus,
  enabled: false,
}
