import type { AdminUserEntitlements, AdminUserRechargeAudit } from '../../api'

function monthStartFor(nowSeconds: number): number {
  const now = new Date(nowSeconds * 1000)
  return Math.floor(new Date(now.getFullYear(), now.getMonth(), 1).getTime() / 1000)
}

function addMonths(monthStart: number, months: number): number {
  const date = new Date(monthStart * 1000)
  date.setMonth(date.getMonth() + months)
  return Math.floor(date.getTime() / 1000)
}

export function createStoryUserRechargeAudit(nowSeconds: number): AdminUserRechargeAudit {
  const monthStart = monthStartFor(nowSeconds)
  const paidAt = nowSeconds - 86_400 * 8 + 600
  const refundOnlyPaidAt = nowSeconds - 86_400 * 14 + 900
  return {
    currentMonthEntitlementCredits: 5_000,
    currentMonthEntitlementHourlyDelta: 100,
    currentMonthEntitlementDailyDelta: 500,
    currentMonthEntitlementMonthlyDelta: 5000,
    effectiveUntilMonthStart: addMonths(monthStart, 2),
    orders: [
      {
        outTradeNo: 'ldc_story_paid_001',
        status: 'paid',
        credits: 3_000,
        months: 3,
        money: '450.00',
        quoteMonthStart: monthStart,
        finalMoneyCents: 45_000,
        finalHourlyDelta: 60,
        finalDailyDelta: 300,
        finalMonthlyDelta: 3000,
        monthEndClampApplied: false,
        tradeNo: 'linuxdo_story_001',
        paymentUrl: null,
        createdAt: nowSeconds - 86_400 * 8,
        payExpiresAt: nowSeconds - 86_400 * 8 + 600,
        cancelAfterAt: nowSeconds - 86_400 * 7,
        cancelledAt: null,
        updatedAt: paidAt,
        paidAt,
        refundedAt: null,
        refundActor: null,
        lastNotifyAt: paidAt + 60,
        refundRetryAfterAt: null,
        refundAttempts: 0,
        lastError: null,
      },
      {
        outTradeNo: 'ldc_story_only_002',
        status: 'refundOnly',
        credits: 2_000,
        months: 2,
        money: '200.00',
        quoteMonthStart: monthStart,
        finalMoneyCents: 20_000,
        finalHourlyDelta: 40,
        finalDailyDelta: 200,
        finalMonthlyDelta: 2000,
        monthEndClampApplied: false,
        tradeNo: 'linuxdo_story_002',
        paymentUrl: null,
        createdAt: nowSeconds - 86_400 * 14,
        payExpiresAt: nowSeconds - 86_400 * 14 + 600,
        cancelAfterAt: nowSeconds - 86_400 * 13,
        cancelledAt: null,
        updatedAt: nowSeconds - 86_400 * 2,
        paidAt: refundOnlyPaidAt,
        refundedAt: nowSeconds - 86_400 * 2,
        refundActor: 'story-admin',
        lastNotifyAt: refundOnlyPaidAt + 60,
        refundRetryAfterAt: null,
        refundAttempts: 0,
        lastError: null,
      },
      {
        outTradeNo: 'ldc_story_expired_003',
        status: 'expired',
        credits: 1_000,
        months: 1,
        money: '30.00',
        quoteMonthStart: monthStart,
        finalMoneyCents: 3_000,
        finalHourlyDelta: 12,
        finalDailyDelta: 60,
        finalMonthlyDelta: 600,
        monthEndClampApplied: true,
        tradeNo: null,
        paymentUrl: null,
        createdAt: nowSeconds - 86_400 * 4,
        payExpiresAt: nowSeconds - 86_400 * 4 + 600,
        cancelAfterAt: nowSeconds - 86_400 * 3,
        cancelledAt: null,
        updatedAt: nowSeconds - 86_400 * 3,
        paidAt: null,
        refundedAt: null,
        refundActor: null,
        lastNotifyAt: null,
        refundRetryAfterAt: null,
        refundAttempts: 0,
        lastError: 'payment entry closed locally after 10 minutes',
      },
      {
        outTradeNo: 'ldc_story_cancelled_004',
        status: 'cancelled',
        credits: 1_000,
        months: 1,
        money: '50.00',
        quoteMonthStart: monthStart,
        finalMoneyCents: 5_000,
        finalHourlyDelta: 20,
        finalDailyDelta: 100,
        finalMonthlyDelta: 1000,
        monthEndClampApplied: false,
        tradeNo: null,
        paymentUrl: null,
        createdAt: nowSeconds - 90_000,
        payExpiresAt: nowSeconds - 89_400,
        cancelAfterAt: nowSeconds - 3_600,
        cancelledAt: nowSeconds - 3_540,
        updatedAt: nowSeconds - 3_540,
        paidAt: null,
        refundedAt: null,
        refundActor: null,
        lastNotifyAt: null,
        refundRetryAfterAt: null,
        refundAttempts: 0,
        lastError: 'order cancelled after 24 hours',
      },
      {
        outTradeNo: 'ldc_story_refunding_005',
        status: 'refunding',
        credits: 1_000,
        months: 1,
        money: '30.00',
        quoteMonthStart: monthStart,
        finalMoneyCents: 3_000,
        finalHourlyDelta: 12,
        finalDailyDelta: 60,
        finalMonthlyDelta: 600,
        monthEndClampApplied: true,
        tradeNo: 'linuxdo_story_005',
        paymentUrl: null,
        createdAt: nowSeconds - 86_400,
        payExpiresAt: nowSeconds - 85_800,
        cancelAfterAt: nowSeconds,
        cancelledAt: null,
        updatedAt: nowSeconds - 120,
        paidAt: nowSeconds - 900,
        refundedAt: null,
        refundActor: 'system:auto',
        lastNotifyAt: nowSeconds - 840,
        refundRetryAfterAt: nowSeconds + 300,
        refundAttempts: 2,
        lastError: 'paid month no longer matches quote month',
      },
    ],
    entitlements: [
      { id: 1, outTradeNo: 'ldc_story_paid_001', monthStart, credits: 3_000, hourlyDelta: 60, dailyDelta: 300, monthlyDelta: 3000, createdAt: paidAt },
      { id: 2, outTradeNo: 'ldc_story_paid_001', monthStart: addMonths(monthStart, 1), credits: 3_000, hourlyDelta: 60, dailyDelta: 300, monthlyDelta: 3000, createdAt: paidAt },
      { id: 3, outTradeNo: 'ldc_story_paid_001', monthStart: addMonths(monthStart, 2), credits: 3_000, hourlyDelta: 60, dailyDelta: 300, monthlyDelta: 3000, createdAt: paidAt },
      { id: 4, outTradeNo: 'ldc_story_only_002', monthStart, credits: 2_000, hourlyDelta: 40, dailyDelta: 200, monthlyDelta: 2000, createdAt: refundOnlyPaidAt },
      { id: 5, outTradeNo: 'ldc_story_only_002', monthStart: addMonths(monthStart, 1), credits: 2_000, hourlyDelta: 40, dailyDelta: 200, monthlyDelta: 2000, createdAt: refundOnlyPaidAt },
    ],
  }
}

export function createStoryUserEntitlements(nowSeconds: number, userId: string): AdminUserEntitlements {
  const monthStart = monthStartFor(nowSeconds)
  return {
    currentMonthStart: monthStart,
    currentBaseDelta: { businessCalls1hDelta: 8, dailyCreditsDelta: 40, monthlyCreditsDelta: 400 },
    currentMonthDelta: { businessCalls1hDelta: 45, dailyCreditsDelta: 280, monthlyCreditsDelta: 2_800 },
    currentPermanentDelta: { businessCalls1hDelta: -5, dailyCreditsDelta: -20, monthlyCreditsDelta: -200 },
    items: [
      {
        id: 80,
        userId,
        scopeKind: 'base',
        monthStart: 0,
        businessCalls1hDelta: 8,
        dailyCreditsDelta: 40,
        monthlyCreditsDelta: 400,
        backendNote: 'Story base quota migration row.',
        frontendNote: 'story base entitlement',
        sourceKind: 'admin',
        sourceId: 'story-admin-base',
        actorUserId: null,
        actorDisplayName: 'story-admin',
        createdAt: nowSeconds - 1_800,
      },
      {
        id: 81,
        userId,
        scopeKind: 'month',
        monthStart,
        businessCalls1hDelta: 45,
        dailyCreditsDelta: 280,
        monthlyCreditsDelta: 2_800,
        backendNote: 'Manual monthly quota correction for story coverage.',
        frontendNote: '补偿本月额度',
        sourceKind: 'admin',
        sourceId: 'story-admin-month',
        actorUserId: null,
        actorDisplayName: 'story-admin',
        createdAt: nowSeconds - 3_600,
      },
      {
        id: 82,
        userId,
        scopeKind: 'permanent',
        monthStart: 0,
        businessCalls1hDelta: -5,
        dailyCreditsDelta: -20,
        monthlyCreditsDelta: -200,
        backendNote: 'Permanent entitlement trim for story coverage.',
        frontendNote: '长期额度校准',
        sourceKind: 'admin',
        sourceId: 'story-admin-permanent',
        actorUserId: null,
        actorDisplayName: 'story-admin',
        createdAt: nowSeconds - 7_200,
      },
    ],
  }
}
